/** Componenti PC. I prezzi NON stanno qui: arrivano dai collector. */

function part(id, title, subtitle, tags, imageTone, listings) {
  return { id, title, subtitle, category: 'pc', tags, imageTone, listings }
}

function amz(q, asin) {
  return {
    store: 'Amazon',
    url: asin ? `https://www.amazon.it/dp/${asin}` : `https://www.amazon.it/s?k=${encodeURIComponent(q)}`,
    externalId: asin || `search-${q.toLowerCase().replace(/\s+/g, '-')}`,
  }
}

function pcc(q) {
  return {
    store: 'PcComponentes',
    url: `https://www.pccomponentes.it/buscar/?query=${encodeURIComponent(q)}`,
    externalId: `pcc-${q.toLowerCase().replace(/\s+/g, '-')}`,
  }
}

export const PC_SEED_PRODUCTS = [
  part(
    'pc-fractal-north',
    'Fractal North',
    'Case mid-tower mesh.',
    ['pc', 'CASE', 'Fractal', 'North', 'mid-tower', 'atx'],
    '#5c4033',
    [amz('Fractal North'), pcc('Fractal North')],
  ),
  part(
    'pc-lianli-lancool-217',
    'Lian Li Lancool 217',
    'Case mid-tower airflow.',
    ['pc', 'CASE', 'Lian Li', 'Lancool', 'mid-tower', 'atx'],
    '#111111',
    [amz('Lian Li Lancool 217'), pcc('Lancool 217')],
  ),
  part(
    'pc-corsair-4000d',
    'Corsair 4000D Airflow',
    'Case mid-tower.',
    ['pc', 'CASE', 'Corsair', '4000D', 'mid-tower', 'atx'],
    '#1b2838',
    [amz('Corsair 4000D Airflow'), pcc('4000D Airflow')],
  ),
  part(
    'pc-nzxt-h5-flow',
    'NZXT H5 Flow',
    'Case mid-tower compatto.',
    ['pc', 'CASE', 'NZXT', 'H5', 'mid-tower', 'atx'],
    '#2b2d42',
    [amz('NZXT H5 Flow'), pcc('NZXT H5 Flow')],
  ),
  part(
    'pc-nr200p',
    'Cooler Master NR200P',
    'Case Mini-ITX.',
    ['pc', 'CASE', 'ITX', 'mini-itx', 'NR200P', 'Cooler Master', 'sff'],
    '#c1121f',
    [amz('Cooler Master NR200P'), pcc('NR200P')],
  ),
  part(
    'pc-ryzen-7800x3d',
    'AMD Ryzen 7 7800X3D',
    'CPU AM5 8 core, cache 3D.',
    ['pc', 'CPU', 'AMD', 'Ryzen', '7800X3D', 'AM5', 'processore'],
    '#7b2d8e',
    [amz('Ryzen 7 7800X3D'), pcc('7800X3D')],
  ),
  part(
    'pc-ryzen-7600',
    'AMD Ryzen 5 7600',
    'CPU AM5 6 core.',
    ['pc', 'CPU', 'AMD', 'Ryzen', '7600', 'AM5', 'processore'],
    '#6a1b9a',
    [amz('Ryzen 5 7600'), pcc('Ryzen 5 7600')],
  ),
  part(
    'pc-ryzen-9700x',
    'AMD Ryzen 7 9700X',
    'CPU AM5 Zen 5.',
    ['pc', 'CPU', 'AMD', 'Ryzen', '9700X', 'AM5', 'processore'],
    '#4a148c',
    [amz('Ryzen 7 9700X'), pcc('9700X')],
  ),
  part(
    'pc-intel-14600k',
    'Intel Core i5-14600K',
    'CPU LGA1700.',
    ['pc', 'CPU', 'Intel', '14600K', 'LGA1700', 'processore'],
    '#0071c5',
    [amz('i5-14600K'), pcc('14600K')],
  ),
  part(
    'pc-intel-265k',
    'Intel Core Ultra 7 265K',
    'CPU LGA1851.',
    ['pc', 'CPU', 'Intel', '265K', 'Ultra', 'LGA1851', 'processore'],
    '#0054a6',
    [amz('Core Ultra 7 265K'), pcc('265K')],
  ),
  part(
    'pc-rtx-5070',
    'NVIDIA GeForce RTX 5070',
    'GPU 50-series.',
    ['pc', 'GPU', 'NVIDIA', 'RTX', '5070', 'scheda video'],
    '#76b900',
    [amz('RTX 5070'), pcc('RTX 5070')],
  ),
  part(
    'pc-rtx-5060ti',
    'NVIDIA GeForce RTX 5060 Ti',
    'GPU fascia media.',
    ['pc', 'GPU', 'NVIDIA', 'RTX', '5060', '5060ti', 'scheda video'],
    '#5a8f00',
    [amz('RTX 5060 Ti'), pcc('RTX 5060 Ti')],
  ),
  part(
    'pc-rtx-5080',
    'NVIDIA GeForce RTX 5080',
    'GPU alta.',
    ['pc', 'GPU', 'NVIDIA', 'RTX', '5080', 'scheda video'],
    '#3d5c00',
    [amz('RTX 5080'), pcc('RTX 5080')],
  ),
  part(
    'pc-rx-9070xt',
    'AMD Radeon RX 9070 XT',
    'GPU RDNA 4.',
    ['pc', 'GPU', 'AMD', 'Radeon', '9070', '9070xt', 'scheda video'],
    '#ed1c24',
    [amz('RX 9070 XT'), pcc('9070 XT')],
  ),
  part(
    'pc-corsair-veng-ddr5-32',
    'Corsair Vengeance DDR5 32GB',
    'Kit 2x16 6000 MHz DIMM.',
    ['pc', 'RAM', 'DDR5', '32GB', 'DIMM', 'Corsair', 'Vengeance', '6000'],
    '#ffd700',
    [amz('Corsair Vengeance DDR5 32GB 6000'), pcc('Vengeance DDR5 32GB')],
  ),
  part(
    'pc-gskill-ddr5-32',
    'G.Skill Trident Z5 DDR5 32GB',
    'Kit 2x16 desktop.',
    ['pc', 'RAM', 'DDR5', '32GB', 'DIMM', 'G.Skill', 'Trident'],
    '#c0c0c0',
    [amz('G.Skill Trident Z5 DDR5 32GB'), pcc('Trident Z5 32GB')],
  ),
  part(
    'pc-kingston-ddr5-64',
    'Kingston Fury Beast DDR5 64GB',
    'Kit 2x32 desktop.',
    ['pc', 'RAM', 'DDR5', '64GB', 'DIMM', 'Kingston', 'Fury'],
    '#1a1a2e',
    [amz('Kingston Fury Beast DDR5 64GB'), pcc('Fury Beast DDR5 64')],
  ),
  part(
    'pc-msi-b650-tomahawk',
    'MSI MAG B650 Tomahawk WiFi',
    'Scheda madre AM5.',
    ['pc', 'MOBO', 'MSI', 'B650', 'AM5', 'scheda madre', 'wifi'],
    '#c8102e',
    [amz('MSI B650 Tomahawk WiFi'), pcc('B650 Tomahawk')],
  ),
  part(
    'pc-asus-tuf-b650',
    'ASUS TUF Gaming B650-PLUS WiFi',
    'Scheda madre AM5.',
    ['pc', 'MOBO', 'ASUS', 'B650', 'AM5', 'scheda madre', 'wifi'],
    '#d4a017',
    [amz('ASUS TUF B650-PLUS'), pcc('TUF B650-PLUS')],
  ),
  part(
    'pc-gigabyte-z890',
    'Gigabyte Z890 Aorus Elite WiFi7',
    'Scheda madre LGA1851.',
    ['pc', 'MOBO', 'Gigabyte', 'Z890', 'LGA1851', 'scheda madre', 'wifi'],
    '#f4a261',
    [amz('Gigabyte Z890 Aorus Elite'), pcc('Z890 Aorus')],
  ),
  part(
    'pc-msi-z790',
    'MSI MAG Z790 Tomahawk WiFi',
    'Scheda madre LGA1700.',
    ['pc', 'MOBO', 'MSI', 'Z790', 'LGA1700', 'scheda madre', 'wifi'],
    '#9b2226',
    [amz('MSI Z790 Tomahawk'), pcc('Z790 Tomahawk')],
  ),
  part(
    'pc-corsair-rm750e',
    'Corsair RM750e',
    'Alimentatore 750W gold.',
    ['pc', 'PSU', 'Corsair', '750W', 'RM750e', 'alimentatore', 'gold'],
    '#f2c14e',
    [amz('Corsair RM750e'), pcc('RM750e')],
  ),
  part(
    'pc-seasonic-focus-850',
    'Seasonic Focus GX-850',
    'Alimentatore 850W.',
    ['pc', 'PSU', 'Seasonic', '850W', 'alimentatore', 'gold'],
    '#1d3557',
    [amz('Seasonic Focus GX-850'), pcc('Focus GX-850')],
  ),
  part(
    'pc-corsair-rm1000e',
    'Corsair RM1000e',
    'Alimentatore 1000W.',
    ['pc', 'PSU', 'Corsair', '1000W', 'RM1000e', 'alimentatore'],
    '#e9c46a',
    [amz('Corsair RM1000e'), pcc('RM1000e')],
  ),
  part(
    'pc-noctua-nhd15',
    'Noctua NH-D15',
    'Dissipatore ad aria.',
    ['pc', 'COOLER', 'Noctua', 'NH-D15', 'aria', 'dissipatore'],
    '#a67c52',
    [amz('Noctua NH-D15'), pcc('NH-D15')],
  ),
  part(
    'pc-thermalright-pa120',
    'Thermalright Peerless Assassin 120',
    'Dissipatore aria.',
    ['pc', 'COOLER', 'Thermalright', 'PA120', 'aria', 'dissipatore'],
    '#8d99ae',
    [amz('Thermalright Peerless Assassin 120'), pcc('Peerless Assassin')],
  ),
  part(
    'pc-arctic-lf3-360',
    'Arctic Liquid Freezer III 360',
    'AIO 360 mm.',
    ['pc', 'COOLER', 'Arctic', 'AIO', '360', 'liquido', 'dissipatore'],
    '#00a3e0',
    [amz('Arctic Liquid Freezer III 360'), pcc('Liquid Freezer III 360')],
  ),
  part(
    'pc-wd-sn850x-2tb',
    'WD Black SN850X 2TB',
    'SSD NVMe PCIe 4.0.',
    ['pc', 'SSD', 'NVMe', '2TB', 'WD', 'SN850X'],
    '#000000',
    [amz('WD Black SN850X 2TB'), pcc('SN850X 2TB')],
  ),
  part(
    'pc-crucial-t500-2tb',
    'Crucial T500 2TB',
    'SSD NVMe.',
    ['pc', 'SSD', 'NVMe', '2TB', 'Crucial', 'T500'],
    '#2b2d42',
    [amz('Crucial T500 2TB'), pcc('Crucial T500 2TB')],
  ),
]
